// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5-9_GwqhSsfLFATf2pgfPwTAH2jPCns',
    appId: '1:301032499758:web:744e88b58f2d67682f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    authDomain: 'finance-a715f.firebaseapp.com',
    storageBucket: 'finance-a715f.firebasestorage.app',
    measurementId: 'G-70Q02EZYR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPDXIY6vc2BegDPlkiM3HWF4EHRsRnhA',
    appId: '1:301032499758:android:26024173c95bc62f2f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    storageBucket: 'finance-a715f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwiFqQk-dm_xYWKL8cy4RqvErA4gwW8us',
    appId: '1:301032499758:ios:bbd69ec1a798d9922f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    storageBucket: 'finance-a715f.firebasestorage.app',
    androidClientId: '301032499758-1n8ndk89d8hgftlajo5qojq9br3jo3tc.apps.googleusercontent.com',
    iosClientId: '301032499758-v8v0adon09r7f3occ89unc5to76ofku6.apps.googleusercontent.com',
    iosBundleId: 'com.example.finances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr5-9_GwqhSsfLFATf2pgfPwTAH2jPCns',
    appId: '1:301032499758:web:80d80e81d4cb61da2f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    authDomain: 'finance-a715f.firebaseapp.com',
    storageBucket: 'finance-a715f.firebasestorage.app',
    measurementId: 'G-K5LR6SK9QY',
  );
}
