// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5-9_GwqhSsfLFATf2pgfPwTAH2jPCns',
    appId: '1:301032499758:web:744e88b58f2d67682f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    authDomain: 'finance-a715f.firebaseapp.com',
    storageBucket: 'finance-a715f.firebasestorage.app',
    measurementId: 'G-70Q02EZYR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqCf1GTz_-znphLA1zG3XbastEsG76ev4',
    appId: '1:301032499758:android:67670d7c95d6f5312f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    storageBucket: 'finance-a715f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwiFqQk-dm_xYWKL8cy4RqvErA4gwW8us',
    appId: '1:301032499758:ios:f1a82a5a2f881a702f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    storageBucket: 'finance-a715f.firebasestorage.app',
    iosBundleId: 'com.example.finances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwiFqQk-dm_xYWKL8cy4RqvErA4gwW8us',
    appId: '1:301032499758:ios:f1a82a5a2f881a702f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    storageBucket: 'finance-a715f.firebasestorage.app',
    iosBundleId: 'com.example.finances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr5-9_GwqhSsfLFATf2pgfPwTAH2jPCns',
    appId: '1:301032499758:web:80d80e81d4cb61da2f8dbf',
    messagingSenderId: '301032499758',
    projectId: 'finance-a715f',
    authDomain: 'finance-a715f.firebaseapp.com',
    storageBucket: 'finance-a715f.firebasestorage.app',
    measurementId: 'G-K5LR6SK9QY',
  );
}
