workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 30
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Initialize iOS Workspace & CocoaPods
        script: |
          flutter build ios --release --no-codesign --config-only
          cd ios && pod install
      - name: Build iOS release
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
