scripts:
      - name: Disable Swift Package Manager
        script: flutter config --no-enable-swift-package-manager
      - name: Get Flutter packages
        script: flutter pub get
      - name: Prepare iOS configuration
        script: flutter build ios --release --no-codesign --config-only
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
artifacts:
      - build/ios/iphoneos/Runner.app