// Archivo de configuración de nivel superior para todas las subproyectos/modules

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Configura las carpetas de build para los módulos locales.
// Se evita redirigir el buildDir de plugins externos ubicados en otras unidades (ej. C:)
// para prevenir el error de Gradle "different roots" en Windows.
rootProject.buildDir = "../build"
subprojects {
    if (project.projectDir.absolutePath.startsWith(rootProject.projectDir.parentFile.absolutePath)) {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    project.evaluationDependsOn(":app")
}

// Limpia la carpeta build
tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
