# Configuración de JVM para Gradle
#org.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=256m
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
# Configuración de AndroidX y Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Configurar Java 17 para Gradle
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
# Solución al error de "different roots"
kotlin.incremental=false
kotlin.incremental.js=false
kotlin.incremental.multiplatform=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
